# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bankdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdata',
            name='amount',
            field=models.FloatField(),
        ),
    ]
